### ISSUE TITLE
Rolling / time based index support

### ISSUE THREAD

**Issue by jagrutmehta** [couchbaselabs/couchbase-elasticsearch-connector#159]
We are in process of upgrading ES which does not have ttl function but has time based rolling index. 
While we successfully created time based daily index and couchbased exposed alias pointing/rolling to new index everyday, plugin keeps on replicating all data over to new index. 

Let say I have alias CB which is configured to receive data in XDCR.
I create ES index on daily bases. Let say day01, day02,.. day31.

Day1: CB -> day01
Day2: CB -> day02

When we change CB to day02, we noticed that day02 gets all of the couchbase data, even those from past. 

I believe it has something to do checkpoint documents. But there is no option in plugin where I can specify this scenario.

**Comment by bgabler** [comment]
@Branor any thoughts on this? We're working with Support trying to find a solution for this. One option is to pass a pipeline_id and we can ingest based on doc.created_at in our case.

https://www.elastic.co/guide/en/elasticsearch/reference/current/pipeline.html
https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest.html

**Comment by jscubida** [comment]
Pipeline support would be great. It'd help me solve [this issue](https://discuss.elastic.co/t/pre-processing-couchbase-documents/107639).

**Comment by dnault** [comment]
@jscubida I see. Looks support for pipelines has value even if it doesn't solve the rolling index issue.

**Comment by jagrutmehta** [comment]
When we copied all checkpoints docs to new index, it did not replicate old docs. 

One suggestion: what if we can tell plugin to store these checkpoints docs to it's own index and normal docs to another rolling alias?

**Comment by dnault** [comment]
> When we copied all checkpoints docs to new index, it did not replicate old docs.
>
> One suggestion: what if we can tell plugin to store these checkpoints docs to it's own index and normal docs to another rolling alias?

Sounds promising. We're investigating this approach.

**Comment by dnault** [comment]
[Version 3.0.0 of the Couchbase plugin for ES](https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/3.0.0-cypress) adds a `couchbase.pipeline` config property for specifying the pipeline name.

After further internal discussion and some much appreciated collaboration with @bgabler, we've determined it should be safe to use a pipeline with [Date Index Name Processor](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/date-index-name-processor.html) to file documents into the appropriate index based on a timestamp field in the document.

This approach has the drawback that documents deleted from Couchbase will not be deleted from ES (since there is not enough info in the deletion notification to determine which index the document lives in). If your application relies on deleting documents, we recommend adding a "deleted" field to the document; instead of deleting a document from couchbase, update it with the "deleted" field set to true. The application reading from ES would then need to be modified to treat such documents as if they did not exist.

> What if we can tell plugin to store these checkpoints docs to it's own index and normal docs to another rolling alias?

To support ES 6.0 we'll need to use separate indexes for checkpoints and documents anyway, since it will no longer be possible to use multiple mappings in the same index. In the meantime, I'd recommend going with the pipeline approach if at all possible.

**Comment by dnault** [comment]
Version 4 of the connector (coming soon as a Developer Preview on August 31st) stores the replication state in Couchbase, and will play nicely with rolling / time based indexes.
